PKG_NAME = libuuid
PKG_VERS = 1.0.3
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://garr.dl.sourceforge.net/project/libuuid
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = 
COMMENT  =
LICENSE  =

GNU_CONFIGURE = 1

#CONFIGURE_TARGET = nope
#INSTALL_TARGET = nope
#PRE_INSTALL_TARGET = nope

#TEST:
#	@echo $(PKG_DIST_NAME)

include ../../mk/spksrc.cross-cc.mk
